#!/usr/bin/env python3
"""sync_counts.py — bake card counts into cards/counts.js

Scans cards/*/cards.js for card urls, fetches the current number for each
from its provider, and writes cards/counts.js (window.BAKED_COUNTS), which
js/hydrate.js applies as the baseline count at page load.

Why offline? Pixiv requires OAuth login and Bilibili's API sends no CORS
headers, so the browser can't call them directly. Run this script whenever
you want fresh numbers:

    python3 tools/sync_counts.py

Credentials come from the environment or a gitignored .env file at the
repo root, and are used by their respective providers only:

    PIXIV_REFRESH_TOKEN   Pixiv likes (pip install pixivpy)
    YOUTUBE_API_KEY       YouTube Data API v3 key

GitHub stars and Bilibili views need no credentials.
"""

import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CARDS_GLOB = "cards/*/cards.js"
OUT = ROOT / "cards" / "counts.js"


def load_env(path):
    """Minimal .env loader (KEY=VALUE per line) — no dependencies."""
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


load_env(ROOT / ".env")

PIXIV_REFRESH_TOKEN = os.environ.get("PIXIV_REFRESH_TOKEN", "")
YOUTUBE_API_KEY = os.environ.get("YOUTUBE_API_KEY", "")

URL_RE = re.compile(r'url:\s*"([^"]+)"')
GH_RE = re.compile(r"github\.com/([\w.-]+/[\w.-]+)")
YT_RE = re.compile(r"(?:youtube\.com/(?:watch\?[^#]*v=|shorts/)|youtu\.be/)([\w-]{11})")
BILI_RE = re.compile(r"bilibili\.com/video/(BV\w+)")
PIXIV_RE = re.compile(r"pixiv\.net/(?:\w+/)?artworks/(\d+)")


def get_json(url, headers=None):
    req = urllib.request.Request(url, headers={
        "User-Agent": "grayworld-sync/1.0", **(headers or {})})
    with urllib.request.urlopen(req, timeout=15) as res:
        return json.load(res)


def github_count(repo):
    return get_json(f"https://api.github.com/repos/{repo}",
                    {"Accept": "application/vnd.github+json"})["stargazers_count"]


def youtube_count(vid, key):
    data = get_json("https://www.googleapis.com/youtube/v3/videos"
                    f"?part=statistics&id={vid}&key={key}")
    return int(data["items"][0]["statistics"]["viewCount"])


def bilibili_count(bvid):
    data = get_json(f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}")
    return int(data["data"]["stat"]["view"])


def pixiv_counts(ids):
    """{illust_id: likes} via pixivpy."""
    try:
        from pixivpy3 import AppPixivAPI
    except ImportError:
        sys.exit("error: pixivpy3 not installed — pip install pixivpy")
    api = AppPixivAPI()
    api.auth(refresh_token=PIXIV_REFRESH_TOKEN)
    out = {}
    for illust_id in ids:
        try:
            out[illust_id] = api.illust_detail(illust_id).illust.total_bookmarks
        except Exception as e:
            print(f"  pixiv {illust_id}: {e}")
    return out


def main():
    urls = []
    for f in sorted(ROOT.glob(CARDS_GLOB)):
        urls += URL_RE.findall(f.read_text(encoding="utf-8"))
    urls = sorted(set(u for u in urls if u.startswith("http")))
    print(f"found {len(urls)} card urls")

    pixiv_ids = [m.group(1) for u in urls if (m := PIXIV_RE.search(u))]
    pixiv = pixiv_counts(pixiv_ids) if pixiv_ids else {}

    counts, failed = {}, 0
    for url in urls:
        try:
            if m := GH_RE.search(url):
                counts[url] = github_count(m.group(1))
            elif m := YT_RE.search(url):
                counts[url] = youtube_count(m.group(1), YOUTUBE_API_KEY)
            elif m := BILI_RE.search(url):
                counts[url] = bilibili_count(m.group(1))
            elif m := PIXIV_RE.search(url):
                if m.group(1) in pixiv:
                    counts[url] = pixiv[m.group(1)]
            else:
                print(f"  ? {url}: no provider matched, skipped")
        except Exception as e:
            failed += 1
            print(f"  ! {url}: {e}")

    OUT.write_text(
        "/* generated by tools/sync_counts.py — do not edit by hand */\n"
        f"window.BAKED_COUNTS = {json.dumps(counts, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(counts)} counts"
          + (f" ({failed} failed)" if failed else ""))


if __name__ == "__main__":
    sys.exit(main())
